name: Nightly HWZ download
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

concurrency:
  group: hwz-commits
  cancel-in-progress: false

jobs:
  download:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@c18668ad3cf93ea998bef934396af7bb5c839dc7 # v10.2.0
      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Install dependencies
        run: |
          make sync
      - name: Run script
        run: |
          uv run scrape.py
      - name: Get current date
        run: |
          echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Run auto-commit action
        uses: stefanzweifel/git-auto-commit-action@4a55954c782fc1ea30b9056cd3e7a2b40ca8887d # v7.2.0
        with:
          commit_message: "Nightly HWZ download ${{ env.NOW }}"
          commit_options: "--no-verify"
          commit_user_name: "luarss"
          commit_user_email: "39641663+luarss@users.noreply.github.com"
          commit_author: "luarss <39641663+luarss@users.noreply.github.com>"
